# Build and push LibHokchew.Shared nuget package

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - dotnet/*

pr:
  branches:
    include:
    - 'master'
  paths:
    include:
    - dotnet/*
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2.208.1
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: 'dotnet/LibHokchew.Shared/src/LibHokchew.Shared.csproj'
    arguments: '-c Release'
- task: NuGetCommand@2
  displayName: nuget pack
  inputs:
    command: 'pack'
    packagesToPack: 'dotnet/LibHokchew.Shared.nuspec'
    versioningScheme: 'off'
- task: NuGetCommand@2
  displayName: nuget push
  condition: and(succeeded() ,eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget'

