package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "hello_hokchew",
    srcs = ["hello_hokchew.py"],
    deps = [
        "//python:pyhokchew"
    ]
)