package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "pyhokchew",
    srcs = glob(["pyhokchew/**/*.py"], exclude = ["pyhokchew/tests/*"])
)