load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "pyhokchew",
    srcs = glob(
        ["pyhokchew/**/*.py"],
        exclude = ["pyhokchew/tests/*"],
    ),
    visibility = ["//visibility:public"],
)
